name: Run Tests
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup environment variables
      env: # Or as an environment variable
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: echo $SERVICE_ACCOUNT > google-credentials.json && echo $ENV_FILE > .env
    - uses: eskatos/gradle-command-action@v1
      with:
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: clean test
